name: Python style
on:
  pull_request:
#    types: [opened]
jobs:
  qa:
    name: Quality check
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: Change __all__ exports for pyflake
        run: |
             bash .github/scripts/pre_pyflakes.sh
      - name: Wemake Python Stylguide
        uses: wemake-services/wemake-python-styleguide@0.15.3
        continue-on-error: false
        with:
          reporter: 'github-pr-review'
        env:
          NUMBA_DISABLE_JIT: 1
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
