# NB! If this action fails with a rather cryptic message about:
#   AttributeError: 'Binding' object has no attribute 'names'
# This is most likely due to the fact that modules were added
# that are not considered in (and one has to patch):
# .github/scripts/pre_pyflakes.sh

name: Python style
on:
  pull_request:
    types: [opened]
  workflow_dispatch:
jobs:
  qa:
    name: Quality check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Change __all__ exports for pyflake
        run: |
             bash .github/scripts/pre_pyflakes.sh
      - name: Set up Python
        uses: actions/setup-python@v4.6.1
        with:
          python-version: 3.8
      - name: patch reviewdog
        run: sudo chown -R root:root $GITHUB_WORKSPACE
      - name: Wemake Python Stylguide
        uses: wemake-services/wemake-python-styleguide@0.18.0
        continue-on-error: true
        with:
          reporter: 'github-pr-review'
        env:
          NUMBA_DISABLE_JIT: 1
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
